cloudstack:
  endpoint: http://localhost:8080/client/api
  api_key: Jfy8RHP1-BddKb0qTBfGJxTm8FQreLjSQvej7nF5XZOnmNzUMA9f9qhbFzBwwsny-XId8Eo56CnYTs-Ws-OoeQ
  secret_access_key: ZZ0lguo0uk2QM5NFncdTQANAm6eyaMemTwyO4xI5j8tQIVzv7zOctNDx81Y7vSfeRb2OY7CGIzv_w6KR4l4AbQ
  default_key_name: xx
  private_key: zz
  state_timeout: 600
  state_timeout_volume: 600
  stemcell_public_visibility: true
  default_zone: TEST2
  
logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR
    
spring:
  main:
    show-banner: true


#cs.endpoint=http://EB-OR7129401.bagnolet.francetelecom.fr:8080/client/
#cs.tenant=tenantxx
#cs.username=Pfq9J0ySWcFWEee_TcK3FzsjtUcquPcVWmmFO_66O_GUARi2HSdJjm6-kpz3ksedwfO2ZO_nxi53jRroBqYXIQ 
#cs.password=d4wPT3TgOt1dhubBJSm7fZtEfM-_9fcUbxg1V7TP_tq6QXQQTAw1y4n1qDLou833baFK4gEAU3tNHgfiOgiD6g


#cs.endpoint: http://192.168.56.11:8080/client
#cs.endpoint: http://localhost:8080/client/api
#cs.username=Jfy8RHP1-BddKb0qTBfGJxTm8FQreLjSQvej7nF5XZOnmNzUMA9f9qhbFzBwwsny-XId8Eo56CnYTs-Ws-OoeQ
#cs.password=ZZ0lguo0uk2QM5NFncdTQANAm6eyaMemTwyO4xI5j8tQIVzv7zOctNDx81Y7vSfeRb2OY7CGIzv_w6KR4l4AbQ
#cs.tenant=tenantxx
  