  
logging:
  level:
    org.springframework: INFO
    org.springframework.boot.actuate: DEBUG
    
spring:
  main:
    show-banner: true
  jackson:
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true    
  profiles:
    active: qa
  pidfile: ./target/application.pid
server:
  tomcat:
    access-log-enabled: true
  

---
spring:
  profiles: default    
cloudstack:
  endpoint: http://192.168.56.11:8080/client/api
  proxy_host:
  proxy_port:
  proxy_user:
  proxy_password:

  api_key: xx
  secret_access_key: yy

  default_key_name: xx
  private_key: zz
  state_timeout: 600
  state_timeout_volume: 600
  stemcell_public_visibility: true
  default_zone: TEST2
    
    
---
spring:
  profiles: qa    
cloudstack:
  endpoint:  http://xxx:8080/client/api
  
  proxy_host: 11.11.11.11
  proxy_port: 8080
  proxy_user: usser
  proxy_password: wwwww
  
  
  
  api_key: xx
  secret_access_key: zz

  default_key_name: xx
  private_key: zz
  state_timeout: 600
  state_timeout_volume: 600
  stemcell_public_visibility: true
  default_zone: ZONE
    