  
logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR
    
spring:
  main:
    show-banner: false
  profiles:
    active: qa

---
spring:
  profiles: default    
cloudstack:
  endpoint: http://192.168.56.11:8080/client/api
  proxy_host:
  proxy_port:
  proxy_user:
  proxy_password:

  api_key: xxxxxxxxxxxxxxx
  secret_access_key: yyyyyyyyyyyyyyy

  default_key_name: xx
  private_key: zz
  state_timeout: 600
  state_timeout_volume: 600
  stemcell_public_visibility: true
  default_zone: TEST2
    
    
---
spring:
  profiles: qa    
cloudstack:
  endpoint:  http://XXX:8080/client/api
  
  proxy_host: YYY
  proxy_port: 8080
  proxy_user: xxxxxxxxxx
  proxy_password: yyyyyyyyyy
  
  
  
  api_key: xxxxxxxxxxxxxxx
  secret_access_key: yyyyyyyyyyyyyyy

  default_key_name: xx
  private_key: zz
  state_timeout: 600
  state_timeout_volume: 600
  stemcell_public_visibility: true
  default_zone: ZONE
    